root = "."
tmp_dir = "tmp"

[build]
cmd = "go run -tags dev ./cmd/healthmon"
full_bin = ""
include_ext = ["go"]
exclude_dir = ["web", "cmd/healthmon/web", "tmp", "vendor", ".git"]

delay = 200

[log]
color = true

[misc]
clean_on_exit = true
